# Generated by Django 3.2.5 on 2021-07-14 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDetailsDatabase',
            fields=[
                ('tokenID', models.AutoField(primary_key=True, serialize=False)),
                ('tokenSymbol', models.CharField(max_length=10)),
                ('tokenName', models.CharField(max_length=50)),
                ('tokenAbi', models.CharField(max_length=5000)),
                ('TokenAddress', models.CharField(max_length=500)),
                ('TokenBlockChain', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='walletDatabase',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserAddress', models.CharField(default='', max_length=500)),
                ('UserTokens', models.CharField(default='', max_length=5000)),
                ('UserSecrete', models.CharField(default='', max_length=3000)),
                ('FroozenNLT', models.FloatField(default='', max_length=100)),
                ('GaruanteedAmt', models.FloatField(default='', max_length=100)),
                ('BorrowaleAmt', models.FloatField(default='', max_length=100)),
                ('ParentAddress', models.CharField(default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
